#
# Module manifest for module 'Reptile'
#
# Generated by: James Brundage
#
# Generated on: 12/27/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Reptile.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '16622757-8355-4457-8807-97bc03cf0b41'

# Author of this module
Author = 'James Brundage'

# Company or vendor of this module
CompanyName = 'Start Automating'

# Copyright statement for this module
Copyright = '2025 Start Automating'

# Description of the functionality provided by this module
Description = 'Read Evaluate Print Terminal Input Loop Editor - A Scaley Simple PowerShell Data REPL.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-Reptile'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Reptile', '🦎','🐊'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/PowerShellWeb/Reptile/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/PowerShellWeb/Reptile'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
## Reptile 0.1:

* Initial Release of Reptile (#1)
* Read Evaluate Print Terminal Input Loop Editor - A Scaley Simple PowerShell Data REPL.
* Reptile is simple (#2) scalable (#3) and mostly safe (#4)
* `Get-Reptile` / `Reptile` / 🦎, 🐊 gets and hatches reptiles (#5, 24)
* Turtle.Reptile is a fun example (#6)
  * Is has limited variable support (#22)
* Calculating Reptile is a safe calculator (#7)
* Days Until Reptile tells time until (#8)
* Gradient Reptile generates gradients (#9)
* Sleepy Reptile shows multiple delayed returns (#26)
* `Get-Reptile` can get a specific `-ReptileName/-Name/-Species` (#17)
* `Get-Reptile` can `-Run` or `-Hatch` a new instance (#18)
* `Reptile` can change its skin (#23)
* `Reptile` returns data in chunks (#25)

'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

